# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ye Lu
email: yl2426@cornell.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome everyone this is my personal space.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github_username:  jimk100

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap